//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBTeknikServisEntities1 : DbContext
    {
        public DBTeknikServisEntities1()
            : base("name=DBTeknikServisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAraclar> TblAraclar { get; set; }
        public virtual DbSet<TblArizaDetay> TblArizaDetay { get; set; }
        public virtual DbSet<TblCari> TblCari { get; set; }
        public virtual DbSet<TblDepartman> TblDepartman { get; set; }
        public virtual DbSet<TblFaturaBilgi> TblFaturaBilgi { get; set; }
        public virtual DbSet<TblFaturaDetay> TblFaturaDetay { get; set; }
        public virtual DbSet<TblGiderler> TblGiderler { get; set; }
        public virtual DbSet<TblKategori> TblKategori { get; set; }
        public virtual DbSet<TblNotlar> TblNotlar { get; set; }
        public virtual DbSet<TblPersonel> TblPersonel { get; set; }
        public virtual DbSet<TblUrun> TblUrun { get; set; }
        public virtual DbSet<TblUrunHareket> TblUrunHareket { get; set; }
        public virtual DbSet<TblUrunKabul> TblUrunKabul { get; set; }
        public virtual DbSet<TblUrunTakip> TblUrunTakip { get; set; }
        public virtual DbSet<Tbliletisim> Tbliletisim { get; set; }
        public virtual DbSet<Tblilceler> Tblilceler { get; set; }
        public virtual DbSet<Tbliller> Tbliller { get; set; }
    
        public virtual ObjectResult<UrunKategori_Result> UrunKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunKategori_Result>("UrunKategori");
        }
    
        public virtual ObjectResult<string> maxUrunKategoriGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maxUrunKategoriGetir");
        }
    }
}
